services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_USER_PASSWORD: ${MARIADB_USER_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./Chuches.sql:/docker-entrypoint-initdb.d/Chuches.sql:ro

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - "48129:80"
    depends_on:
      - mariadb

  python:
    build: ./api
    container_name: python
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    depends_on:
      - mariadb

  apache-waf:
    build: ./apache
    container_name: apache-waf
    ports:
      - "48123:80"
    depends_on:
      - python

volumes:
  mariadb_data:
