services:
  mariadb:
    image: mariadb
    container_name: mariadb-b7
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_USER_PASSWORD: ${MARIADB_USER_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./Chuches.sql:/docker-entrypoint-initdb.d/Chuches.sql:ro

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-b7
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb-b7
    ports:
      - "7107:80"
    depends_on:
      - mariadb

  python:
    build: ./api
    container_name: python-b7
    restart: unless-stopped
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: mariadb-b7
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
      PASSWORD_PEPPER: ${PASSWORD_PEPPER}
      SECRET_KEY: ${SECRET_KEY}                      
      WTF_CSRF_SECRET_KEY: ${WTF_CSRF_SECRET_KEY}  
    depends_on:
      - mariadb

  apache-waf:
    build: ./apache
    container_name: apache-waf-b7
    restart: unless-stopped
    ports:
      - "6107:80"
      - "6443:443"
    depends_on:
      - python

volumes:
  mariadb_data:
