LoadModule evasive20_module /usr/lib/apache2/modules/mod_evasive20.so

<IfModule mod_evasive20.c>
    DOSHashTableSize    3097
    DOSPageCount        5
    DOSSiteCount        50
    DOSPageInterval     1
    DOSSiteInterval     1
    DOSBlockingPeriod   10
    DOSLogDir           /var/log/mod_evasive
</IfModule>

# Límites y timeouts
MaxKeepAliveRequests 100
Timeout 300
RequestReadTimeout header=20-40,MinRate=500 body=20,MinRate=500

<IfModule mpm_event_module>
    MaxRequestWorkers 8192
    MaxConnectionsPerChild 10000
</IfModule>

<IfModule mpm_prefork_module>
    MaxClients 8192
    MaxRequestsPerChild 10000
</IfModule>

<VirtualHost *:80>
    RewriteEngine On
    RewriteRule ^(.*)$ https://localhost:6443$1 [R=301,L]
</VirtualHost>

<VirtualHost *:443>
    SSLEngine on
    SSLCertificateFile /usr/local/apache2/conf/ssl/server.crt
    SSLCertificateKeyFile /usr/local/apache2/conf/ssl/server.key

    ProxyPass /api/ http://python:8080/api/
    ProxyPassReverse /api/ http://python:8080/api/

    DocumentRoot /var/www/html/
    <Directory /var/www/html/>
        DirectoryIndex index.html
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    CustomLog /proc/self/fd/1 common
    ErrorLog /proc/self/fd/2
</VirtualHost>