FROM httpd:2.4.33-alpine
RUN apk update; \
    apk upgrade;
# Copy apache vhost file to proxy php requests to php-fpm container
COPY demo.apache.conf /usr/local/apache2/conf/demo.apache.conf
COPY ./static/ /var/www/html
RUN echo "Include /usr/local/apache2/conf/demo.apache.conf" \
    >> /usr/local/apache2/conf/httpd.conf

    # Dar permisos correctos a la web
RUN chmod 755 /var \
&& chmod 755 /var/www \
&& chmod -R 755 /var/www/html
